default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 1234
  port: 5432

development:
  <<: *default
  database: bodybalance_development
  #username: bodybalance_db_admin


test:
  <<: *default
  database: bodybalance_test